### ISSUE TITLE
loading loops issue

### ISSUE THREAD

**Issue by sa501428** [aidenlab/Juicebox#709]
Assembly mode hides small contigs.
But this means that loops loaded won't show up at low resolution.
This will look as though the loop list is empty to users.​
Either this should be disabled when not in assembly mode, or some notification needs to be passed to users.

**Comment by dudcha** [comment]
You can enlarge annotations to show all. Overall it is a matter of separating defaults: sparse should be default only for assembly.

**Comment by sa501428** [comment]
resolved via 73c939191b8fd504efa3834e4f52426cb9c7e3a9
