### ISSUE TITLE
error loading .hic file

### ISSUE THREAD

**Issue by RuiqinZheng** [aidenlab/Juicebox#720]
Hi
When I load a .hic file to juicebox ,it called "error loading .hic file".
the .hic file is produced by hicpro2jucier.sh in the HiC-Pro software. when I use it to Arabidopsis, it works,but when I use it to Rice, error happened.
So I don't know why .
hope you reply soon!
Best wishes!

**Comment by RuiqinZheng** [comment]
sorry, I have solve it !
that's because I don't download the complete .hic file

**Comment by sqwwww** [comment]
> sorry, I have solve it ! that's because I don't download the complete .hic file

thanks, it helps me.
