### ISSUE TITLE
juicer_tools dump norm requires chromosome to be specified?

### ISSUE THREAD

**Issue by theaidenlab** [aidenlab/Juicebox#721]
From @johnstonmj
https://github.com/theaidenlab/JuiceboxLegacy/issues/13

From the [Data Extraction examples](https://github.com/theaidenlab/juicer/wiki/Data-Extraction) it appears that specifying an argument for chr is optional for "dump norm" and that without it should default to All Chromosomes without an argument specified.

However, I found that I had to put chr = all for it to work.
Otherwise, I got a NullPointerException.

# Works
/path/to/juicer_tools dump norm KR /path/to/file/inter_30.hic **all** BP 25000 dump_norm_KR_all_25kb.txt

# Fails
/path/to/juicer_tools dump norm KR /path/to/file/inter_30.hic BP 25000 dump_norm_KR_noAll_567_25kb.txt

Exception in thread "main" java.lang.NullPointerException
	at juicebox.tools.clt.old.Dump.extractChromosomeRegionIndices(Dump.java:455)
	at juicebox.tools.clt.old.Dump.readArguments(Dump.java:347)
	at juicebox.tools.HiCTools.main(HiCTools.java:97)

**Comment by sa501428** [comment]
@johnstonmj I don't see where it says the chromosome is optional. The x1:x2 notation is the optional part.
