### ISSUE TITLE
eigenvector's results can't be loaded by Juicebox

### ISSUE THREAD

**Issue by QianzhaoJ** [aidenlab/Juicebox#751]
Hi,
I got compartments result by using  juicer ,but  when I tried to load these output files on Juicebox , I failed. Why was this happening?
Thank you in advance.

**Comment by sa501428** [comment]
Hi, please post this question to our forum: aidenlab.org/forum.html
Github is for verified bug reports only.
Thanks!

PS. Also please let us know what file type you are trying to load.
