### ISSUE TITLE
problems with macOS native intergration in Info.plist

### ISSUE THREAD

**Issue by core-code** [aidenlab/Juicebox#779]
Juicebox doesn't have a "bundle identifier" (aka CFBundleIdentifier) in its Info.plist file.

as per apple's guidelines ( https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102070 ) all Mac apps should have a bundle identifier, else things like implicit caching are broken.

also, the version information of the 1.9.8 release seems to be off, both the name of the disk image and the version information in the app itself claim its really version 1.9.1:

```
    <key>CFBundleShortVersionString</key>
    <string>1.9.1</string>
```

**Comment by nchernia** [comment]
Next dmg online will have version number fixed as well

**Comment by core-code** [comment]
awesome, thanks ;)
