### ISSUE TITLE
Exporting a PDF

### ISSUE THREAD

**Issue by kai3192** [aidenlab/Juicebox#780]
Is there a way to zoom out on the screen while exporting as a PDF ?

I have a small screen and all of the 200kb resolution map dosen't fit in the screen. So when I trty to export it as a PDF or SVG only the part that is visible on the screen is being exported rather than the entire map.

Kaivalya

**Comment by sa501428** [comment]
This would require dumping the data using juicer tools or straw / not supported at present in Juicebox
