### ISSUE TITLE
Adding header check for 2D annotations

### ISSUE THREAD

**Issue by johnstonmj** [aidenlab/Juicebox#782]
Upon display in Juicebox, the first row of a headerless 2D annotation bedpe is absent.
Tested and reproduced in Juicebox_1.8.8.exe + Juicebox_1.9.8.exe.
The same issue is not present in Juicebox.js
My guess is that the first row is skipped as an assumed header line.

I have been working with intersections of bedpe files using bedtools pairtopair.
The default result is a headerless bedpe.
Now that I am aware of this, it is easy enough to add a header row, but fixing this could help others in the future.
Can a header be tested for rather than auto-skipping the first line?
Or a headerless option?

Thanks!

**Comment by sa501428** [comment]
yes that makes sense (i.e. adding check for header)

**Comment by sa501428** [comment]
resolved
