### ISSUE TITLE
error when loading 1D annotation

### ISSUE THREAD

**Issue by xiaoshen19930901** [aidenlab/Juicebox#795]
Dear friends:
when i load 1D annotations ,no matter  bed bedgraph bw 
this error "nould not load resource <br>null  " will occur

To tell the truth, i really wonder the right format which i should have to put in 1D annotiaon, becaouse most of them could be opened in IGV ~

Wish your good news, thank you !

**Comment by jrobinso** [comment]
Thanks for the report,  I will investigate.   Could you check the javascript console for further messages, including possibly line numbers?

When you say "could be opened in IGV",  are you referring to the desktop or web IGV?

**Comment by xiaoshen19930901** [comment]
The version is 1.9.8 in windows10, java is 1.8.0-152
the desktop IGV

**Comment by jrobinso** [comment]
First, apologies,  I didn't look carefully at the repository and thought this was a juicebox.js issue.  Someone else will be in contact about the Juicebox desktop issue.

Off topic but that is a very old version of IGV.

**Comment by xiaoshen19930901** [comment]
Thank you for your attention and patient , maybe i will wait for another answer~

**Comment by sa501428** [comment]
can you post this to our forum first? aidenlab.org/forum.html
please include a brief example of a 1D track that is failing

**Comment by xiaoshen19930901** [comment]
thank you so much ! i will do that
