### ISSUE TITLE
Bin randomization

### ISSUE THREAD

**Issue by sa501428** [aidenlab/Juicebox#809]
Randomization errors encountered: ___ no map found, ___ two different maps found
This statement should only be printed if the bin randomization flag is passed in, not by default.

**Comment by zyqfrog10** [comment]
Hello, 

Recently I transformed HiCPro output into .hic with a fragment file. Everything ran smoothly and the results could be loaded into juicebox without any problem. But when I checked the log file, there was one line "Randomization errors encountered: 0 no map found, 0 two different maps found." 

I'm trying to understand the randomization process here. Looks like in 'Preprocessor.java', initially it is set as 'allowPositionsRandomization = false', and I did't see anywhere this boolean got changed. So the position randomization seems like not triggered ever letting 'noMapFoundCount = 0, and mapDifferentCount = 0.' I may miss something here. Could you help explain this? 
Thanks,
Ada

**Comment by sa501428** [comment]
Hi @zyqfrog10 bin randomization is not performed by default and requires specific flags. There are no issues with your file.

**Comment by zyqfrog10** [comment]
Thanks so much for the quick clarification! That confirms my thinking.
