### ISSUE TITLE
download issue

### ISSUE THREAD

**Issue by Antony-1996** [aidenlab/Juicebox#819]
Hello ? I encountered a problem when I download Juicebox to linux systerm . After I uncompress the jar file ,I cannot find the command to use juciebox . 
![image](https://user-images.githubusercontent.com/43497334/57596279-673dab00-757c-11e9-9743-db3e9f45cf8f.png)

**Comment by nchernia** [comment]
Hello - you shouldn't uncompress the jar. Type `java -jar Juicebox.jar` to run it. You probably want to give it at least 2G of memory. Here's an example with 16g:

```
java -Xmx16000m -jar Juicebox.jar
```

**Comment by Antony-1996** [comment]
thank you so much，I will try it
