### ISSUE TITLE
How to generate both .hic and .assembly files ?

### ISSUE THREAD

**Issue by wlhCNU** [aidenlab/Juicebox#837]
hi,
Now, I have a ordering orientation genome final.fasta file and the .bam file. Is it possible for us to generate .hic and .assembly files?
Thanks

**Comment by LIZW2019** [comment]
hi,
I don't know whether you have solve it. I just come into the same problem and somehow work it out, so I came to write my answer. Hope it will help you or others too.

1. with the fasta and original fastq of hic library you can get the hic using the juicer as follow:
(find [juicer](https://github.com/aidenlab/juicerl))
`bwa index <fasta>`
`generate_site_positions.py HindIII modify_final <fasta>`
genereate fasta_contig_length,formatted as contig name and length seperated by ",\t". put the fastq into a folder name "fastq" before the following step.
`juicer.sh -g <fasta_contig_length> -s <enzyme> -z <fasta> -y <last_step_output> -p <fasta_contig_length>`
this step will come out with two folder named "aligned" and "splits"
`juicer_tools pre aligned/merged_nodups.txt modify_final.hic <fasta_contig_length>`
.hic get!!

2. assembly got using a little script in 3d-dna pipeline:
(find [3d-dna](https://github.com/theaidenlab/3d-dna))
awk -f ~/software/3d-dna/utils/generate-assembly-file-from-fasta.awk ../modify_final.fa
and .assembly get

**Comment by dudcha** [comment]
See Genome Assembly Cookbook hosted on dnazoo.org/methods for instructions on how to use our assembly tools.
