### ISSUE TITLE
Many anomalous contacts in heatmap (& slightly off chromosome borders) 

### ISSUE THREAD

**Issue by sjfleck** [aidenlab/Juicebox#868]
I've tried many different parameters in 3d-dna and I haven't had a better assembly than simply altering the editor coarse resolution to 100,000 (I've lowered the number of contigs further, but the N50 also lowers). That being said, none of my maps look as clean as the maps you have created in your tutorial. Also, when I zoom into the the chromosome edges, they seem to be slightly off. I've been fixing them manually in Juicebox, but it's very time consuming. I was wondering if you had any suggestions. Thank you.

Heat map for all default parameters except editor coarse resolution = 100000:
![3d_dna_FF_01_mds_--ecr100000](https://user-images.githubusercontent.com/53409202/71533304-fa3a1400-28c5-11ea-9b47-671a1c002647.jpeg)

an excel file for many of the parameters I've tried:
[3d_dna_progress_FF.xlsx](https://github.com/aidenlab/Juicebox/files/4006307/3d_dna_progress_FF.xlsx)

**Comment by sa501428** [comment]
Hi,
This appears to be a general question, not a bug. 
Please post this to our forum: aidenlab.org/forum.html
Thanks!
