### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chrisdrogaris** [aidenlab/Juicebox#872]
**Describe the bug**
I am unable to load this url http://hicfiles.s3.amazonaws.com/external/GM12878_CTCF_orientation.bed

**To Reproduce**
1. Go to https://github.com/aidenlab/Juicebox/blob/5a56089c63957cb15401ea7906ab77e242dfd755/src/juicebox/track/tracksMenu_hg19.xml
2. Load that url from bottom 

**Expected behavior**
Link not to be broken

**Screenshots**
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>26FF6F91AFF32942</RequestId>
<HostId>
jm3AWNc6ZEDxQ+c5REhcLtNnuZodyasn+i27oIsIFVgbqN/e4YGlf/pzjEQ9PSv+SUrWdtmNyhs=
</HostId>
</Error>

**Desktop (please complete the following information):**
 - OS: Mac

**Additional context**
n/a

**Comment by sa501428** [comment]
Hey @chrisdrogaris
General questions should be posted to the forum: [http://aidenlab.org/forum.html](http://aidenlab.org/forum.html). I'm unable to see the screenshots, but if you're trying to download the files, please use the GEO Mirror. See [http://aidenlab.org/data.html](http://aidenlab.org/data.html)
