### ISSUE TITLE
.FINAL.assembly slow to load in Juicebox

### ISSUE THREAD

**Issue by jphruska** [aidenlab/Juicebox#877]
Hi--

I've been having a hard time loading and examining a version of my genome in Juicebox that was just run through the run-asm-post-review. Both the FINAL.assembly (361 KB) and FINAL.hic (922 MB) files are not significantly larger than ones that were loaded and manipulated without trouble prior to running the run-asm-post-review (e.g., 329 KB and 911 MB, respectively), which leads me to believe this is not a file size issue. Is there something else that may be causing this problem?   

Any help would be greatly appreciated. 

Thanks
Jack

**Comment by nchernia** [comment]
Hello and sorry for the delay - please post this on the forum aidenlab.org/forum.html and someone will get back to you.
