### ISSUE TITLE
need help for very unrelated scaffoold  [BUG]

### ISSUE THREAD

**Issue by longzhangnation** [aidenlab/Juicebox#907]
Hi , I am sorry to post my question here because I don't have access to Google forum for my situations when I use JBAT. It works file for my genome , whose size is 1Gb, heterozygosity about 1.3% . When I view the assembly on JBAT , I notice that some small scaffolds are not related to other saffolds but the software still put them in the same chromosome . So how should I deal with the small scaffolds ? Should I move them to debris ? or any other ? if anybody has asked about it , you can give me a link to , I will check my self. The detailed pictures is attached .
[JBAT_error.docx](https://github.com/aidenlab/Juicebox/files/4752331/JBAT_error.docx)

**Comment by dudcha** [comment]
Hello,

This is not a bug. This is the code making mistakes when trying to split the assembly into chromosomes. From the figure you are sharing it is hard to say what is causing the error. You can use JBAT to move to debris or to to move to the actual position in the genome as suggested by the contact frequency (if such position exists that is).

Olga
