### ISSUE TITLE
Is there a away to cut contigs with "debris" label?

### ISSUE THREAD

**Issue by TypicalSEE** [aidenlab/Juicebox#908]
Hi, I'm using Juicebox to modify my draft assembly. I loaded ".final.hic" and ".final.assembly" files generated by 3D-DNA pipeline to Juicebox. But I found thst some contigs with "debris" label can not be cut into two pieces. According to issue #775 , contigs with "debris" label are not allowed to be edited. But the contigs do need to be cut. So what should I do to cut the contigs? Thanks!

**Comment by dudcha** [comment]
Hello,

You can manually remove the debris label in the assembly file and edit after that.

Olga
