### ISSUE TITLE
JBAT - I'm only able to edit the first scaffold

### ISSUE THREAD

**Issue by Dikaryotic** [aidenlab/Juicebox#922]
I've got an assembly .hic and .assembly file that I'm trying to correct in JBAT. I can load the .hic file and .assembly files fine, but I'm only able to edit the very first scaffold. I'm using version 1.11.08 of JBAT. When I shift click on scaffold one it works, but when I try that for every other scaffold it just zooms in. I've looked through the manual and supporting documents and feel like I mustve missed something! 

Help?

**Comment by dudcha** [comment]
JBAT only works with assembly chromosome format. Check the genome assembly cookbook (dnazoo.org/methods) page 5 for instructions on how to build one.

Best,
Olga

**Comment by Dikaryotic** [comment]
Ok, thanks for that Olga. I had been running the 3D-DNA pipeline in parallel. I've gotten to running the run-asm-pipeline.sh script but I'm getting this error: 

Not sure how to parse your input: files not listed or not found at expected locations. Exiting. 

That occurs when I run it with the files in the same directory as the script and when I run it in another directory:
run-asm-pipeline.sh curated.fasta merged_nodups.txt
run-asm-pipeline.sh ../curated.fasta ../merged_nodups.txt

Any suggestions on what's occurring here? I've even provided absolute file paths for my files with no luck. I'm using version 180922 on a linux box.

**Comment by dudcha** [comment]
If you just want to do JBAT you don’t have to run all of 3D-DNA. You just need to run the visualization module. See page 5 instructions on how to generate the assembly file and visualize.

Re errors make sure the files Alsace proper permissions set. The error suggests it cannot read either the fasta or the mnd file.

Olga

**Comment by Dikaryotic** [comment]
I've just tried running the visualization step as suggested but have hit the same error as before. I've checked my file permissions with ls -l and gotten this: 

drwxrwxr-x 16 osboxes osboxes     4096 Sep  2 22:31 3d-dna
-rwxrwxrwx  1 osboxes osboxes 39044142 Sep  1 21:22 curated.fa
-rwxrwxrwx  1 osboxes osboxes     2018 Sep  2 22:36 draft.assembly
-rwxrwxrwx  1 osboxes osboxes        0 Sep  1 21:22 merged_nodups.txt

So everything looks fine there. 


Cheers,
Chris

**Comment by dudcha** [comment]
Looks like your mnd is empty.

**Comment by Dikaryotic** [comment]
That's it! Thanks. I'd run the first part of the pipeline with untrimmed and trimmed data and had forgotten the trimmed data set had something go wrong. I've just gone and started running it with the original untrimmed set and it's running fine. 

Thankyou so much for the help! I just knew it was going to be something obvious but I couldn't figure out what. 


Cheers,
Chris

**Comment by dudcha** [comment]
No problem. Good luck, Chris, -Olga
