### ISSUE TITLE
New debris sequences cause issues with fasta conversion

### ISSUE THREAD

**Issue by ValentinaBoP** [aidenlab/Juicebox#934]
Hi!

I'm using Juicebox to curate a ~1Gb genome assembly. Everything works alright, I managed to fix all the major issues then I exported the new .assembly file. I used the script `juicebox_assembly_converter.py` (that I used several times before) to get the new fasta file:

`python juicebox_assembly_converter.py -f genome.fasta -a genome_review.assembly -p genome_Vale_curation`

I get this error:

```
Processing assembly file. Details:
Assembly:			genome_review.assembly
Fasta:				genome.fasta
Output prefix:			genome_Vale_curation
Contig mode:			False
Simple Chromosome Names:	False

Reading sequences from genome.fasta...
.................
Sequences read

Reading .assembly file genome_review.assembly...
.assembly read


Checking for breaks listed in .assembly and making them...
Traceback (most recent call last):
  File "juicebox_assembly_converter.py", line 835, in <module>
    simple_chr_names=simple_chr_names)
  File "juicebox_assembly_converter.py", line 82, in process
    sequences = self._add_breaks(sequences, assembly_map)
  File "juicebox_assembly_converter.py", line 256, in _add_breaks
    raise ContigNotFoundError('Could not find contig {0} in original FASTA'.format(fragment))
__main__.ContigNotFoundError: Could not find contig ('scaffold1,53300474,f1092z879475k27a0.11m10_f890Z45256689k41a0.80m10_f82z485318k793a0.32m10_f1142z894238k155a0.70m10_r1946z5687815k401a0.64m10_r501z96939:::fragment_10:::debris', '12999') in original FASTA
```

It does not find a specific debris sequence but I'm sure I'm using the right files. Testing some strategies, what I found is that specifically when I cut `scaffold1[...]:::fragment_7` this `fragment_10:::debris` is de-novo created (I checked its existence before and after cutting, it exists only after I cut that specific sequence) therefore the converter script does not find the new sequence in the original fasta file.

Do you have any suggestions to fix this problem? I also tried to purge those specific debris but then I discovered that fragments have been renamed by Juicebox -- e.g. scaffold1[...]fragment_9 was renamed into scaffold1[...]fragment_11, name that did not exist in the original fasta file -- so more and more sequences are not being found in the original fasta file.

-- Java just got updated on my Mac, could it be linked to this problem?

Thank you a lot for your help :)

Valentina

**Comment by dudcha** [comment]
Hi Valentina,

We didn’t write the converter script you are referencing, so we cannot answer to any issues you are experiencing with it. (I believe this is Phase Genomics script?) I suggest you try the 3D-DNA run-asm-pipeline-post-review script, as suggested by the Genome Assembly Cookbook. Please do not forget to cite the relevant papers for Juicebox Assembly Tools and 3D-DNA.

Thanks,
Olga

----
Olga Dudchenko, PhD
M&H Genetics/Aiden Lab
Baylor College of Medicine
olga.dudchenko@bcm.edu<mailto:olga.dudchenko@bcm.edu>

On Dec 23, 2020, at 3:59 AM, Valentina <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi!

I'm using Juicebox to curate a ~1Gb genome assembly. Everything works alright, I managed to fix all the major issues then I exported the new .assembly file. I used the script juicebox_assembly_converter.py (that I used several times before) to get the new fasta file:

python juicebox_assembly_converter.py -f genome.fasta -a genome_review.assembly -p genome_Vale_curation

I get this error:

Processing assembly file. Details:
Assembly:                       genome_review.assembly
Fasta:                          genome.fasta
Output prefix:                  genome_Vale_curation
Contig mode:                    False
Simple Chromosome Names:        False

Reading sequences from genome.fasta...
.................
Sequences read

Reading .assembly file genome_review.assembly...
.assembly read


Checking for breaks listed in .assembly and making them...
Traceback (most recent call last):
  File "juicebox_assembly_converter.py", line 835, in <module>
    simple_chr_names=simple_chr_names)
  File "juicebox_assembly_converter.py", line 82, in process
    sequences = self._add_breaks(sequences, assembly_map)
  File "juicebox_assembly_converter.py", line 256, in _add_breaks
    raise ContigNotFoundError('Could not find contig {0} in original FASTA'.format(fragment))
__main__.ContigNotFoundError: Could not find contig ('scaffold1,53300474,f1092z879475k27a0.11m10_f890Z45256689k41a0.80m10_f82z485318k793a0.32m10_f1142z894238k155a0.70m10_r1946z5687815k401a0.64m10_r501z96939:::fragment_10:::debris', '12999') in original FASTA


It does not find a specific debris sequence but I'm sure I'm using the right files. Testing some strategies, what I found is that specifically when I cut scaffold1[...]:::fragment_7 this fragment_10:::debris is de-novo created (I checked its existence before and after cutting, it exists only after I cut that specific sequence) therefore the converter script does not find the new sequence in the original fasta file.

Do you have any suggestions to fix this problem? I also tried to purge those specific debris from the assembly file and it works but at the same time I'm not happy with losing sequences from my genome assembly.

Thank you a lot for your help :)

Valentina

**Comment by ValentinaBoP** [comment]
I see, thanks Olga! Now I'm trying to run the run-asm-pipeline-post-review script
