### ISSUE TITLE
Error loading .hic file from Gdrive to web Juicebox 

### ISSUE THREAD

**Issue by aminakur** [aidenlab/Juicebox#959]
I cannot upload the .hic file from my Google Drive to the web version of Juicebox (file size 1.5Gb if that matters). I get an error 404. When I upload the same file from my computer to web Juicebox, it works ok.

**Comment by sa501428** [comment]
Hi @BeetleMilk 
Please post this bug report to the following repo: https://github.com/igvteam/juicebox.js
