### ISSUE TITLE
error loading .hic file

### ISSUE THREAD

**Issue by yuanyuanhe2021** [aidenlab/Juicebox#966]
Hi, I created a .hic file from HiC-Pro output by hicpro2juice.sh,  but when I loaded it to juicebox, it errors:
`error loading .hic file`
![图片](https://user-images.githubusercontent.com/89682561/131946197-1b6a3b86-98ba-4b02-a1d4-e8bae8bad733.png)
I was wondering how could I solve it?
Thank you so much

**Comment by sa501428** [comment]
Can you confirm if the file works with Juicebox web? aidenlab.org/juicebox
This error is likely due to requiring the latest Juicebox version.
You can use the Juicebox jar from the latest release.
We will also work on updating the executables

**Comment by yuanyuanhe2021** [comment]
> Can you confirm if the file works with Juicebox web? aidenlab.org/juicebox
> This error is likely due to requiring the latest Juicebox version.
> You can use the Juicebox jar from the latest release.
> We will also work on updating the executables

Thanks a lot for your reply! I updated my juicebox and now it works well.

**Comment by zmz1988** [comment]
Hi @sa501428 , I also got the same error, when I tried both jar and Mac 1.11.08 version of Juicebox. However, the web version works, but I can't manage the assembly in the web version. Could you help me out please?

Btw, not sure whether it's related, I use the Mac with the M1 Apple chip.

**Comment by sa501428** [comment]
Juicebox versions 1.x can only read files built from Juicer Tools versions 1.x. You will need to use a Juicebox 2.x jar to read files built with Juicer Tools 2.x. These can be found under `https://github.com/aidenlab/Juicebox/releases`

For assembly/JBAT purposes, we recommend using the version of the jar included with 3D-DNA, which should be 1.x. The 2.x versions are under active development, and so things may break.
